---
name: Lint & Unit

"on":
  pull_request:
  push:
    branches:
      - main

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Run yaml Lint
        uses: actionshub/yamllint@main

  chefstyle:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        ruby: ["3.1"]
    name: Chefstyle on Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - uses: r7kamura/rubocop-problem-matchers-action@v1
      - run: bundle exec chefstyle

  unit:
    name: Unit test on Ruby ${{ matrix.ruby }}
    needs: [yamllint, chefstyle]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["3.1"]
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake spec
